name: Preview artifact
on:
  pull_request:
    paths:
      - index.bs
      - .github/workflows/deploy-github-pages.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  preview-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install bikeshed && bikeshed update
      - id: configure-pages
        uses: actions/configure-pages@v3
      - shell: bash {0}
        run: |
          timeout 5 bikeshed watch 2>&1 | tee $GITHUB_STEP_SUMMARY
          # â˜ This is a hack to override the fatal errors. Use 'bikeshed spec'.
          sed -e 's/\x1b\[[0-9;]*m//g' -i $GITHUB_STEP_SUMMARY
          sed -i '1s;^;```sh\n;' $GITHUB_STEP_SUMMARY
          echo $'\n```' >> $GITHUB_STEP_SUMMARY
          test -f index.html
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - uses: actions/upload-artifact@v3
        with:
          name: preview-artifact
          path: .
